# Generated by Django 3.0.8 on 2022-04-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='createdby',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
